@extends('layouts.control')
@section('title', $member->exists ? __('journal.edit_editorial_member') : __('journal.add_editorial_member'))
@push('styles')<link rel="stylesheet" href="{{ asset('assets/css/iuoamc-journal-1.0.0.css') }}">@endpush
@section('content')<div class="journal-control">@include('control.journal._nav')
<section class="page-heading"><div><span class="eyebrow">MCIJ / BOARD RECORD</span><h1>{{ $member->exists ? __('journal.edit_editorial_member') : __('journal.add_editorial_member') }}</h1><p>{{ __('journal.editorial_member_consent_help') }}</p></div></section>
@if($errors->any())<div class="alert alert-error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<section class="data-card"><form class="journal-stack-form" method="post" action="{{ $member->exists ? route('journal.control.editorial-members.update',['locale'=>app()->getLocale(),'editorial_member'=>$member]) : route('journal.control.editorial-members.store',['locale'=>app()->getLocale()]) }}">@csrf @if($member->exists)@method('put')@endif
<div class="journal-form-grid"><label>{{ __('journal.name') }}<input name="name" required maxlength="255" value="{{ old('name',$member->name) }}"></label><label>{{ __('journal.editorial_role') }}<select name="role" required>@foreach(\App\Models\JournalEditorialMember::ROLES as $role)<option value="{{ $role }}" @selected(old('role',$member->role)===$role)>{{ __('journal.board_roles.'.$role) }}</option>@endforeach</select></label><label>{{ __('journal.status') }}<select name="status" required>@foreach(['draft','active'] as $status)<option value="{{ $status }}" @selected(old('status',$member->status?:'draft')===$status)>{{ __('journal.board_statuses.'.$status) }}</option>@endforeach</select></label><label>{{ __('journal.sort_order') }}<input type="number" name="sort_order" min="1" max="1000" required value="{{ old('sort_order',$member->sort_order?:100) }}"></label><label>{{ __('journal.country_code') }}<input name="country_code" maxlength="2" value="{{ old('country_code',$member->country_code) }}"></label><label>ORCID<input name="orcid" maxlength="25" value="{{ old('orcid',$member->orcid) }}"></label></div>
@foreach(['ar'=>'العربية','en'=>'English','fr'=>'Français'] as $language=>$label)<fieldset><legend>{{ $label }}</legend><div class="journal-form-grid"><label>{{ __('journal.professional_title') }}<input name="title_{{ $language }}" maxlength="255" value="{{ old('title_'.$language,($member->title??[])[$language]??'') }}"></label><label>{{ __('journal.affiliation') }}<input name="affiliation_{{ $language }}" maxlength="500" value="{{ old('affiliation_'.$language,($member->affiliation??[])[$language]??'') }}"></label></div><label>{{ __('journal.biography') }}<textarea name="biography_{{ $language }}" maxlength="3000">{{ old('biography_'.$language,($member->biography??[])[$language]??'') }}</textarea></label></fieldset>@endforeach
<label class="journal-check"><input type="checkbox" name="consent_confirmed" value="1" @checked(old('consent_confirmed',$member->consented_at!==null))> {{ __('journal.consent_confirmation') }}</label><button class="primary-action">{{ __('journal.save_editorial_member') }}</button></form></section>
@if($member->exists)<section class="data-card"><form class="journal-stack-form" method="post" action="{{ route('journal.control.editorial-members.archive',['locale'=>app()->getLocale(),'editorial_member'=>$member]) }}">@csrf<textarea name="reason" required maxlength="1000" placeholder="{{ __('journal.archive_reason') }}"></textarea><button class="secondary-action">{{ __('journal.archive_appointment') }}</button></form></section>@endif
</div>@endsection
