@extends('layouts.control')
@section('title', __('certificate_catalog.collections_title'))
@section('content')
<div class="pc-module" dir="{{ app()->getLocale()==='ar'?'rtl':'ltr' }}">
<header class="pc-heading"><div><span class="pc-eyebrow">{{ __('certificate_catalog.collections_title') }}</span><h1><bdi>{{ $collection['program_title'] }}</bdi></h1><p><bdi dir="ltr">{{ $collection['achievement_date'] }}</bdi> · {{ $members->count() }} {{ __('certificate_catalog.record_count') }} · {{ $collection['batches']->count() }} {{ __('certificate_catalog.collection_batches') }}</p></div><a class="pc-button pc-button-secondary" href="{{ route('certificates.batches.index',['locale'=>app()->getLocale()]) }}">{{ __('certificates.back') }}</a></header>
@include('control.pro_certificates._tabs')
<section class="pc-card pc-collection-card"><header class="pc-card-heading"><div><h2>{{ __('certificate_catalog.collection_certificates') }}</h2><p>{{ __('certificate_catalog.collection_integrity_notice') }}</p></div><span class="pc-badge pc-state-issued">{{ $members->where('status','issued')->count() }} {{ __('certificates.states.issued') }}</span></header><div class="pc-table-scroll"><table class="pc-table"><thead><tr><th>#</th><th>{{ __('certificates.recipient_name') }}</th><th>{{ __('certificates.number') }}</th><th>{{ __('certificates.status') }}</th><th>{{ __('certificates.actions_label') }}</th></tr></thead><tbody>
@foreach($members as $certificate)<tr><td>{{ $loop->iteration }}</td>@if($checks[$certificate->id])<td><strong><bdi>{{ $certificate->recipient_name }}</bdi></strong><small><bdi>{{ $certificate->specialization }}</bdi></small></td><td><bdi dir="ltr">{{ $certificate->certificate_number ?: '—' }}</bdi></td><td><span class="pc-badge pc-state-{{ $statuses[$certificate->id] }}">{{ __('certificates.states.'.$statuses[$certificate->id]) }}</span></td><td><div class="pc-table-links"><a class="pc-text-link" href="{{ route('certificates.show',['locale'=>app()->getLocale(),'certificate'=>$certificate->id]) }}">{{ __('certificates.open') }}</a>@if(in_array($certificate->status,['issued','revoked'],true))<a class="pc-text-link" href="{{ route('certificates.download',['locale'=>app()->getLocale(),'certificate'=>$certificate->id]) }}">PDF</a><a class="pc-text-link" href="{{ route('certificates.image',['locale'=>app()->getLocale(),'certificate'=>$certificate->id,'variant'=>'print']) }}">PNG 300 DPI</a><a class="pc-text-link" href="{{ route('certificates.image',['locale'=>app()->getLocale(),'certificate'=>$certificate->id,'variant'=>'share']) }}">JPG</a><a class="pc-text-link" href="{{ route('pro-certificates.verify',['token'=>$certificate->public_token,'lang'=>app()->getLocale()]) }}" target="_blank" rel="noopener noreferrer">{{ __('certificates.verify_link') }}</a>@endif</div></td>@else<td colspan="4">{{ __('certificates.integrity_failed') }}</td>@endif</tr>@endforeach
</tbody></table></div></section>
<section class="pc-card"><header class="pc-card-heading"><div><h2>{{ __('certificate_catalog.source_batches') }}</h2><p>{{ __('certificate_catalog.source_batches_help') }}</p></div></header>@if($collection['batches']->isNotEmpty())<div class="pc-collection-sources">@foreach($collection['batches'] as $batch)<a href="{{ route('certificates.batches.show',['locale'=>app()->getLocale(),'batch'=>$batch->id]) }}"><span>#{{ $batch->id }}</span><strong><bdi>{{ $batch->label }}</bdi></strong></a>@endforeach</div>@else<div class="pc-empty"><p>{{ __('certificate_catalog.no_source_batches') }}</p></div>@endif</section>
</div>
@endsection
