@extends('layouts.control')
@section('title', $batch->label)
@section('content')
<div class="pc-module" dir="{{ app()->getLocale()==='ar'?'rtl':'ltr' }}">
<header class="pc-heading"><div><span class="pc-eyebrow">{{ __('certificate_catalog.batch_title') }}</span><h1><bdi>{{ $batch->label }}</bdi></h1><p>{{ $batch->organization?->display_name }} · {{ $members->count() }} {{ __('certificate_catalog.record_count') }}</p></div><a class="pc-button pc-button-secondary" href="{{ route('certificates.batches.index',['locale'=>app()->getLocale()]) }}">{{ __('certificates.back') }}</a></header>
@include('control.pro_certificates._tabs')
@include('control.pro_certificates._messages')
<div class="pc-stats"><div><span>{{ __('certificates.states.draft') }}</span><strong>{{ $eligible['submit'] }}</strong></div><div><span>{{ __('certificates.states.review') }}</span><strong>{{ $eligible['approve'] }}</strong></div><div><span>{{ __('certificates.states.approved') }}</span><strong>{{ $eligible['issue'] }}</strong></div></div>
@if($run)
<section class="pc-card pc-run-panel" @if($run->status==='running' && (int)$run->actor_id===(int)auth()->id()) data-pc-run data-endpoint="{{ route('certificates.runs.step',['locale'=>app()->getLocale(),'run'=>$run->id]) }}" data-run-id="{{ $run->id }}" data-auto-start="{{ (int)session('certificate_run_started')===(int)$run->id?'1':'0' }}" data-message-running="{{ __('certificate_catalog.run_running') }}" data-message-complete="{{ __('certificate_catalog.run_complete_message') }}" data-message-stopped="{{ __('certificate_catalog.run_stopped') }}" data-message-paused="{{ __('certificate_catalog.run_paused') }}" data-message-network="{{ __('certificate_catalog.run_network') }}" data-message-auth="{{ __('certificate_catalog.run_auth') }}" data-message-conflict="{{ __('certificate_catalog.run_conflict') }}" data-message-failure="{{ __('certificate_catalog.run_failure') }}" @endif>
<header class="pc-card-heading"><div><h2>{{ __('certificate_catalog.run_progress') }} — {{ __('certificate_catalog.batch_'.$run->action) }}</h2><p data-pc-run-message role="status" aria-live="polite">{{ __('certificate_catalog.run_'.$run->status) }}</p></div><strong data-pc-run-count><bdi dir="ltr">{{ $run->done }} / {{ $run->total }}</bdi></strong></header>
<progress class="pc-run-progress" data-pc-run-progress value="{{ $run->done }}" max="{{ max(1,$run->total) }}" aria-label="{{ __('certificate_catalog.run_progress') }}"></progress>
<div class="pc-button-row">@if($run->status==='running' && (int)$run->actor_id===(int)auth()->id())<input type="hidden" data-pc-run-csrf value="{{ csrf_token() }}"><button type="button" class="pc-button pc-button-primary" data-pc-run-resume>{{ __('certificate_catalog.run_resume') }}</button><button type="button" class="pc-button pc-button-secondary" data-pc-run-pause hidden>{{ __('certificate_catalog.run_pause') }}</button>@elseif($run->status==='running')<p class="pc-help">{{ __('certificate_catalog.run_owner_only') }}</p>@endif<a class="pc-text-link" href="{{ route('certificates.batches.show',['locale'=>app()->getLocale(),'batch'=>$batch->id]) }}">{{ __('certificate_catalog.refresh_status') }}</a></div>
<noscript><p class="pc-notice pc-notice-warning">{{ __('certificate_catalog.run_nojs') }}</p></noscript>
</section>
@endif
<section class="pc-card"><header class="pc-card-heading"><div><h2>{{ __('certificate_catalog.batch_details') }}</h2><p>{{ __('certificate_catalog.batch_review_help') }}</p></div></header><div class="pc-table-scroll"><table class="pc-table"><thead><tr><th>#</th><th>{{ __('certificates.recipient_name') }}</th><th>{{ __('certificates.public_name') }}</th><th>{{ __('certificate_catalog.specialization') }}</th><th>{{ __('certificates.number') }}</th><th>{{ __('certificates.status') }}</th><th>{{ __('certificates.actions_label') }}</th></tr></thead><tbody>
@foreach($members as $certificate)<tr><td>{{ $loop->iteration }}</td>@if($checks[$certificate->id])<td><bdi>{{ $certificate->recipient_name }}</bdi></td><td><bdi>{{ $certificate->public_name }}</bdi></td><td><bdi>{{ ($certificate->specialization!==null && $certificate->specialization!=='') ? $certificate->specialization : '—' }}</bdi></td><td><bdi dir="ltr">{{ $certificate->certificate_number ?: '—' }}</bdi></td><td><span class="pc-badge pc-state-{{ $statuses[$certificate->id] }}">{{ __('certificates.states.'.$statuses[$certificate->id]) }}</span></td><td><div class="pc-table-links"><a class="pc-text-link" href="{{ route('certificates.show',['locale'=>app()->getLocale(),'certificate'=>$certificate->id]) }}">{{ __('certificates.open') }}</a>@if(in_array($certificate->status,['draft','review','approved'],true)&&auth()->user()->canDo('certificates.manage'))<a class="pc-text-link" href="{{ route('certificates.preview',['locale'=>app()->getLocale(),'certificate'=>$certificate->id]) }}" target="_blank" rel="noopener noreferrer">{{ __('certificates.preview') }}</a>@elseif(in_array($certificate->status,['issued','revoked'],true))<a class="pc-text-link" href="{{ route('certificates.download',['locale'=>app()->getLocale(),'certificate'=>$certificate->id]) }}">{{ __('certificates.download') }}</a>@endif</div></td>@else<td colspan="6">{{ __('certificates.integrity_failed') }}</td>@endif</tr>@endforeach
</tbody></table></div></section>
@if(!$run || $run->status!=='running')
<section class="pc-card"><header class="pc-card-heading"><div><h2>{{ __('certificates.workflow') }}</h2><p>{{ __('certificate_catalog.batch_action_help') }}</p></div></header><div class="pc-batch-actions">
@foreach(['submit'=>'certificates.manage','approve'=>'certificates.review','issue'=>'certificates.issue'] as $action=>$permission)
@if(auth()->user()->canDo($permission)&&$eligible[$action]>0)
<form method="post" action="{{ route('certificates.batches.start',['locale'=>app()->getLocale(),'batch'=>$batch->id]) }}" class="pc-batch-action">@csrf<input type="hidden" name="action" value="{{ $action }}"><input type="hidden" name="fingerprint" value="{{ $fingerprint }}"><h3>{{ __('certificate_catalog.batch_'.$action) }}</h3><p>{{ $eligible[$action] }} {{ __('certificate_catalog.eligible_count') }}</p><label class="pc-confirm"><input type="checkbox" name="confirm" value="1" required><span>{{ __('certificate_catalog.batch_confirm_'.$action) }}</span></label><button class="pc-button {{ $action==='issue'?'pc-button-primary':'pc-button-secondary' }}" type="submit">{{ __('certificate_catalog.batch_'.$action) }}</button></form>
@endif
@endforeach
</div></section>
@endif
</div>
@endsection
