@extends('layouts.control')
@php($translation=$article->translation())
@php($blindReviewer=auth()->user()->hasRole('journal-reviewer') && !auth()->user()->canDo('journal.manage'))
@section('title', $translation?->title)
@push('styles')<link rel="stylesheet" href="{{ asset('assets/css/iuoamc-journal-1.0.0.css') }}">@endpush
@section('content')
<div class="journal-control">@include('control.journal._nav')
<section class="page-heading"><div><span class="eyebrow"><bdi dir="ltr">{{ $article->article_code }}</bdi></span><h1>{{ $translation?->title }}</h1><p><span class="journal-type journal-type-{{ $article->type }}">{{ __('journal.types.'.$article->type) }}</span> <span class="status-badge status-{{ $article->status }}">{{ __('journal.statuses.'.$article->status) }}</span></p></div><div class="heading-actions">@if(in_array($article->status,['draft','revision_required'],true) && auth()->user()->canDo('journal.manage'))<a class="primary-action" href="{{ route('journal.control.articles.edit',['locale'=>app()->getLocale(),'article'=>$article]) }}">{{ __('journal.edit_article') }}</a>@endif @if(in_array($article->status,['published','retracted'],true))<a class="secondary-action" target="_blank" href="{{ route('journal.public.articles.show',['locale'=>app()->getLocale(),'article'=>$article->slug]) }}">{{ __('journal.public_view') }} ↗</a>@endif</div></section>
<div class="journal-control-grid"><section class="data-card"><div class="data-card-header"><div><h2>{{ __('journal.record_details') }}</h2></div></div><dl class="journal-facts"><div><dt>{{ __('journal.status') }}</dt><dd>{{ __('journal.statuses.'.$article->status) }}</dd></div><div><dt>{{ __('journal.type') }}</dt><dd>{{ __('journal.types.'.$article->type) }}</dd></div><div><dt>{{ __('journal.author') }}</dt><dd>{{ $blindReviewer ? __('journal.blinded_for_review') : $article->authors->pluck('name')->join(', ') }}</dd></div><div><dt>{{ __('journal.issue') }}</dt><dd>{{ $article->issue ? 'V'.$article->issue->volume.' / N'.$article->issue->number : '—' }}</dd></div><div><dt>DOI</dt><dd>{{ $article->doi ?: __('journal.not_assigned') }}</dd></div><div><dt>{{ __('journal.version_of_record') }}</dt><dd>V{{ $article->version_of_record }}</dd></div><div class="wide"><dt>SHA-256</dt><dd><bdi dir="ltr">{{ $article->version_of_record_hash ?: '—' }}</bdi></dd></div></dl></section>
<aside class="data-card"><div class="data-card-header"><div><h2>{{ __('journal.workflow') }}</h2><p>{{ $article->type==='professional_article' ? __('journal.professional_publish_help') : __('journal.workflow_help') }}</p></div></div>
@foreach($actions as $action)@if((in_array($action,['accept','reject','publish','publish_professional','retract'],true) && auth()->user()->canDo('journal.publish')) || (!in_array($action,['accept','reject','publish','publish_professional','retract'],true) && auth()->user()->canDo('journal.manage')))<form class="journal-action" method="post" action="{{ route('journal.control.articles.transition',['locale'=>app()->getLocale(),'article'=>$article]) }}">@csrf<input type="hidden" name="lock_version" value="{{ $article->lock_version }}"><input type="hidden" name="action" value="{{ $action }}">@if(in_array($action,['accept','request_revision','reject','retract'],true))<textarea name="reason" @required(in_array($action,['request_revision','reject','retract'],true)) maxlength="3000" placeholder="{{ $action==='accept' ? __('journal.decision_letter_optional') : __('journal.reason_required') }}"></textarea>@endif<button class="{{ in_array($action,['publish','publish_professional','accept'],true)?'primary-action':'secondary-action' }}" type="submit">{{ __('journal.actions.'.$action) }}</button></form>@endif @endforeach
@if(in_array($article->status,['published','retracted'],true) && auth()->user()->canDo('journal.publish'))<form class="journal-action correction-action" method="post" action="{{ route('journal.control.articles.corrections.store',['locale'=>app()->getLocale(),'article'=>$article]) }}">@csrf<textarea name="reason" required maxlength="3000" placeholder="{{ __('journal.correction_reason') }}"></textarea><button class="secondary-action">{{ __('journal.create_correction') }}</button></form>@endif</aside></div>
@if(!$blindReviewer)
<section class="data-card journal-publication-control">
    <div class="data-card-header"><div><h2>{{ __('journal.publication_assets') }}</h2><p>{{ __('journal.publication_assets_help') }}</p></div></div>
    <dl class="journal-facts">
        <div><dt>{{ __('journal.wicp_number') }}</dt><dd><bdi dir="ltr">{{ $article->wicp_registration_number ?: '—' }}</bdi>@if(\Illuminate\Support\Str::startsWith((string) $article->wicp_registration_number, \App\Models\JournalArticle::WICP_TEST_PREFIX)) <span class="status-badge">{{ __('journal.wicp_test_number') }}</span>@endif</dd></div>
        <div><dt>{{ __('journal.wicp_registered_at') }}</dt><dd>{{ $article->wicp_registered_at?->format('Y-m-d') ?: '—' }}</dd></div>
        <div class="wide"><dt>{{ __('journal.pdf_fingerprint') }}</dt><dd><bdi dir="ltr">{{ $article->pdf_sha256 ?: '—' }}</bdi></dd></div>
    </dl>
    @if(!in_array($article->status,['published','retracted'],true) && auth()->user()->canDo('journal.manage'))
    <form class="institutional-form" method="post" enctype="multipart/form-data" action="{{ route('journal.control.articles.publication-assets',['locale'=>app()->getLocale(),'article'=>$article]) }}">@csrf
        <div class="form-grid two-columns">
            <label class="field"><span>{{ __('journal.publication_pdf') }} *</span><input type="file" name="publication_pdf" accept="application/pdf,.pdf" required><small>{{ __('journal.publication_pdf_help') }}</small></label>
            <label class="field"><span>DOI</span><input name="doi" maxlength="255" dir="ltr" placeholder="10.xxxx/identifier" value="{{ old('doi',$article->doi) }}"><small>{{ __('journal.doi_verified_only') }}</small></label>
            <label class="field"><span>{{ __('journal.wicp_number') }} *</span><input name="wicp_registration_number" maxlength="120" dir="ltr" required value="{{ old('wicp_registration_number',$article->wicp_registration_number) }}"></label>
            <label class="field"><span>{{ __('journal.wicp_registered_at') }} *</span><input type="date" name="wicp_registered_at" required value="{{ old('wicp_registered_at',$article->wicp_registered_at?->format('Y-m-d')) }}"></label>
            <label class="field"><span>{{ __('journal.wicp_verification_url') }}</span><input type="url" name="wicp_verification_url" dir="ltr" maxlength="1000" value="{{ old('wicp_verification_url',$article->wicp_verification_url) }}"></label>
            <label class="field wide consent-check"><input type="checkbox" name="wicp_verified" value="1" required><span>{{ __('journal.wicp_verification_confirmed') }}</span></label>
        </div>
        <button class="primary-action" type="submit">{{ __('journal.save_publication_assets') }}</button>
    </form>
    @endif
</section>
@endif
<section class="data-card journal-preview"><div class="data-card-header"><div><h2>{{ __('journal.content_preview') }}</h2></div></div><h3>{{ $translation?->title }}</h3><strong>{{ __('journal.abstract') }}</strong><p>{!! nl2br(e($translation?->abstract)) !!}</p></section>
@if(!$blindReviewer && $article->decisions->isNotEmpty())<section class="data-card"><div class="data-card-header"><div><h2>{{ __('journal.editorial_decisions') }}</h2><p>{{ __('journal.editorial_decisions_help') }}</p></div></div><div class="journal-decision-list">@foreach($article->decisions as $decision)<article><header><strong>{{ __('journal.statuses.'.$decision->decision) }}</strong><time>{{ $decision->issued_at->format('Y-m-d H:i') }} UTC</time></header><p>{{ $decision->letter ?: __('journal.no_decision_letter') }}</p><small>{{ __('journal.issued_by') }}: {{ $decision->issuer->name }}</small></article>@endforeach</div></section>@endif
@if($article->type==='peer_reviewed_research')<section class="data-card"><div class="data-card-header"><div><h2>{{ __('journal.peer_review_records') }}</h2><p>{{ __('journal.peer_review_help') }}</p></div></div>
@if($article->status==='under_review' && auth()->user()->canDo('journal.manage'))<form class="journal-filter" method="post" action="{{ route('journal.control.reviews.store',['locale'=>app()->getLocale(),'article'=>$article]) }}">@csrf<select name="reviewer_id" required><option value="">{{ __('journal.choose_reviewer') }}</option>@foreach($reviewers as $reviewer)<option value="{{ $reviewer->id }}">{{ $reviewer->name }} — {{ $reviewer->email }}</option>@endforeach</select><input type="number" name="round" min="1" max="20" value="1" required><input type="date" name="due_at"><button class="secondary-action">{{ __('journal.assign_reviewer') }}</button></form>@endif
<div class="journal-review-list">@forelse($article->reviews as $review)<article><header><strong>{{ __('journal.review_round',['round'=>$review->round]) }}</strong><span class="status-badge">{{ __('journal.review_statuses.'.$review->status) }}</span></header><p>{{ __('journal.reviewer') }}: {{ $review->reviewer->name }}</p>@if($review->due_at)<p>{{ __('journal.review_due') }}: {{ $review->due_at->format('Y-m-d') }}</p>@endif @if($review->status==='submitted')<p>{{ __('journal.recommendation') }}: {{ __('journal.recommendations.'.$review->recommendation) }}</p><blockquote>{{ $review->author_comments }}</blockquote>@elseif($review->reviewer_id===auth()->id() && $review->status==='invited')<form class="journal-action" method="post" action="{{ route('journal.control.reviews.respond',['locale'=>app()->getLocale(),'review'=>$review]) }}">@csrf<input type="hidden" name="response" value="accept"><button class="primary-action">{{ __('journal.accept_review') }}</button></form><form class="journal-action" method="post" action="{{ route('journal.control.reviews.respond',['locale'=>app()->getLocale(),'review'=>$review]) }}">@csrf<input type="hidden" name="response" value="decline"><textarea name="decline_reason" required maxlength="2000" placeholder="{{ __('journal.decline_reason') }}"></textarea><button class="secondary-action">{{ __('journal.decline_review') }}</button></form>@elseif($review->reviewer_id===auth()->id() && $review->status==='in_progress')<form class="journal-action" method="post" action="{{ route('journal.control.reviews.update',['locale'=>app()->getLocale(),'review'=>$review]) }}">@csrf @method('put')<select name="recommendation" required>@foreach(['accept','minor_revision','major_revision','reject'] as $recommendation)<option value="{{ $recommendation }}">{{ __('journal.recommendations.'.$recommendation) }}</option>@endforeach</select><textarea name="author_comments" required maxlength="20000" placeholder="{{ __('journal.author_comments') }}"></textarea><textarea name="confidential_comments" maxlength="20000" placeholder="{{ __('journal.confidential_comments') }}"></textarea><button class="primary-action">{{ __('journal.submit_review') }}</button></form>@endif</article>@empty<div class="journal-empty">{{ __('journal.no_reviews') }}</div>@endforelse</div></section>@endif
</div>
@endsection
