@extends('layouts.control')
@php($translation=$article->translation())
@php($blindReviewer=auth()->user()->hasRole('journal-reviewer') && !auth()->user()->canDo('journal.manage'))
@section('title', $translation?->title)
@push('styles')<link rel="stylesheet" href="{{ asset('assets/css/iuoamc-journal-1.0.0.css') }}">@endpush
@section('content')
<div class="journal-control">@include('control.journal._nav')
<section class="page-heading"><div><span class="eyebrow"><bdi dir="ltr">{{ $article->article_code }}</bdi></span><h1>{{ $translation?->title }}</h1><p><span class="journal-type journal-type-{{ $article->type }}">{{ __('journal.types.'.$article->type) }}</span> <span class="status-badge status-{{ $article->status }}">{{ __('journal.statuses.'.$article->status) }}</span></p></div><div class="heading-actions">@if(in_array($article->status,['draft','revision_required'],true) && auth()->user()->canDo('journal.manage'))<a class="primary-action" href="{{ route('journal.control.articles.edit',['locale'=>app()->getLocale(),'article'=>$article]) }}">{{ __('journal.edit_article') }}</a>@endif @if(in_array($article->status,['published','retracted'],true))<a class="secondary-action" target="_blank" href="{{ route('journal.public.articles.show',['locale'=>app()->getLocale(),'article'=>$article]) }}">{{ __('journal.public_view') }} ↗</a>@endif</div></section>
<div class="journal-control-grid"><section class="data-card"><div class="data-card-header"><div><h2>{{ __('journal.record_details') }}</h2></div></div><dl class="journal-facts"><div><dt>{{ __('journal.status') }}</dt><dd>{{ __('journal.statuses.'.$article->status) }}</dd></div><div><dt>{{ __('journal.type') }}</dt><dd>{{ __('journal.types.'.$article->type) }}</dd></div><div><dt>{{ __('journal.author') }}</dt><dd>{{ $blindReviewer ? __('journal.blinded_for_review') : $article->authors->pluck('name')->join(', ') }}</dd></div><div><dt>{{ __('journal.issue') }}</dt><dd>{{ $article->issue ? 'V'.$article->issue->volume.' / N'.$article->issue->number : '—' }}</dd></div><div><dt>DOI</dt><dd>{{ $article->doi ?: __('journal.not_assigned') }}</dd></div><div><dt>{{ __('journal.version_of_record') }}</dt><dd>V{{ $article->version_of_record }}</dd></div><div class="wide"><dt>SHA-256</dt><dd><bdi dir="ltr">{{ $article->version_of_record_hash ?: '—' }}</bdi></dd></div></dl></section>
<aside class="data-card"><div class="data-card-header"><div><h2>{{ __('journal.workflow') }}</h2><p>{{ __('journal.workflow_help') }}</p></div></div>@php($actions=['draft'=>['submit'],'submitted'=>['screen'],'initial_screening'=>$article->type==='peer_reviewed_research'?['send_review','request_revision']:['accept','request_revision'],'under_review'=>['accept','request_revision'],'revision_required'=>['resubmit'],'accepted'=>['copyedit'],'copyediting'=>['typeset'],'typesetting'=>['ready'],'ready_to_publish'=>['publish'],'published'=>['retract']][$article->status]??[])@foreach($actions as $action)@if((in_array($action,['accept','publish','retract'],true) && auth()->user()->canDo('journal.publish')) || (!in_array($action,['accept','publish','retract'],true) && auth()->user()->canDo('journal.manage')))<form class="journal-action" method="post" action="{{ route('journal.control.articles.transition',['locale'=>app()->getLocale(),'article'=>$article]) }}">@csrf<input type="hidden" name="lock_version" value="{{ $article->lock_version }}"><input type="hidden" name="action" value="{{ $action }}">@if(in_array($action,['request_revision','retract'],true))<textarea name="reason" required maxlength="3000" placeholder="{{ __('journal.reason_required') }}"></textarea>@endif<button class="{{ in_array($action,['publish','accept'],true)?'primary-action':'secondary-action' }}" type="submit">{{ __('journal.actions.'.$action) }}</button></form>@endif @endforeach
@if(in_array($article->status,['published','retracted'],true) && auth()->user()->canDo('journal.publish'))<form class="journal-action correction-action" method="post" action="{{ route('journal.control.articles.corrections.store',['locale'=>app()->getLocale(),'article'=>$article]) }}">@csrf<textarea name="reason" required maxlength="3000" placeholder="{{ __('journal.correction_reason') }}"></textarea><button class="secondary-action">{{ __('journal.create_correction') }}</button></form>@endif</aside></div>
<section class="data-card journal-preview"><div class="data-card-header"><div><h2>{{ __('journal.content_preview') }}</h2></div></div><h3>{{ $translation?->title }}</h3><strong>{{ __('journal.abstract') }}</strong><p>{!! nl2br(e($translation?->abstract)) !!}</p></section>
@if($article->type==='peer_reviewed_research')<section class="data-card"><div class="data-card-header"><div><h2>{{ __('journal.peer_review_records') }}</h2><p>{{ __('journal.peer_review_help') }}</p></div></div>
@if($article->status==='under_review' && auth()->user()->canDo('journal.manage'))<form class="journal-filter" method="post" action="{{ route('journal.control.reviews.store',['locale'=>app()->getLocale(),'article'=>$article]) }}">@csrf<select name="reviewer_id" required><option value="">{{ __('journal.choose_reviewer') }}</option>@foreach($reviewers as $reviewer)<option value="{{ $reviewer->id }}">{{ $reviewer->name }} — {{ $reviewer->email }}</option>@endforeach</select><input type="number" name="round" min="1" max="20" value="1" required><input type="date" name="due_at"><button class="secondary-action">{{ __('journal.assign_reviewer') }}</button></form>@endif
<div class="journal-review-list">@forelse($article->reviews as $review)<article><header><strong>{{ __('journal.review_round',['round'=>$review->round]) }}</strong><span class="status-badge">{{ __('journal.review_statuses.'.$review->status) }}</span></header><p>{{ __('journal.reviewer') }}: {{ $review->reviewer->name }}</p>@if($review->status==='submitted')<p>{{ __('journal.recommendation') }}: {{ __('journal.recommendations.'.$review->recommendation) }}</p><blockquote>{{ $review->author_comments }}</blockquote>@elseif($review->reviewer_id===auth()->id())<form class="journal-action" method="post" action="{{ route('journal.control.reviews.update',['locale'=>app()->getLocale(),'review'=>$review]) }}">@csrf @method('put')<select name="recommendation" required>@foreach(['accept','minor_revision','major_revision','reject'] as $recommendation)<option value="{{ $recommendation }}">{{ __('journal.recommendations.'.$recommendation) }}</option>@endforeach</select><textarea name="author_comments" required maxlength="20000" placeholder="{{ __('journal.author_comments') }}"></textarea><textarea name="confidential_comments" maxlength="20000" placeholder="{{ __('journal.confidential_comments') }}"></textarea><button class="primary-action">{{ __('journal.submit_review') }}</button></form>@endif</article>@empty<div class="journal-empty">{{ __('journal.no_reviews') }}</div>@endforelse</div></section>@endif
</div>
@endsection
