(()=>{
  const STORAGE_KEY='iuoamc_nexus_lang';
  const supported=['ar','en','fr'];
  const skipTags=new Set(['SCRIPT','STYLE','NOSCRIPT','CODE','PRE']);
  const exact={ar:{},fr:{}};
  const add=(en,ar,fr)=>{exact.ar[en]=ar;exact.fr[en]=fr};

  [
    ['IUOAMC Broadcast Nexus','منظومة بث IUOAMC','IUOAMC Broadcast Nexus'],
    ['Mission-Critical Operations','عمليات البث الحرجة','Opérations critiques'],
    ['Overview','نظرة عامة','Vue d’ensemble'],['Live Studio','الاستوديو المباشر','Studio en direct'],['WebRTC Lab','مختبر WebRTC','Laboratoire WebRTC'],['Channels','القنوات','Chaînes'],['Scheduler','الجدولة','Planificateur'],['Media Library','مكتبة الوسائط','Médiathèque'],['Playout','التشغيل','Diffusion'],['Encoder','المُرمِّز','Encodeur'],['Distribution','التوزيع','Distribution'],['NOC','مركز عمليات الشبكة','Centre NOC'],['Failover','التحويل الاحتياطي','Basculement'],['Supervisor','المشرف','Superviseur'],['System Health','صحة النظام','Santé du système'],
    ['Operations Overview','نظرة عامة على العمليات','Vue d’ensemble des opérations'],['Unified control surface for Broadcast Nexus staging.','واجهة تحكم موحّدة لبيئة Broadcast Nexus التجريبية.','Surface de contrôle unifiée pour l’environnement de préproduction Broadcast Nexus.'],['STAGING','تجريبي','PRÉPRODUCTION'],['STAGING ONLY','بيئة اختبار فقط','PRÉPRODUCTION UNIQUEMENT'],['PRODUCTION SWITCHING OFF','التحويل للإنتاج متوقف','BASCULEMENT PRODUCTION DÉSACTIVÉ'],['PRODUCTION OUTPUTS OFF','مخرجات الإنتاج متوقفة','SORTIES DE PRODUCTION DÉSACTIVÉES'],['PUBLIC PUBLISHING OFF','النشر العام متوقف','PUBLICATION PUBLIQUE DÉSACTIVÉE'],['EXTERNAL OUTPUTS LOCKED','المخرجات الخارجية مقفلة','SORTIES EXTERNES VERROUILLÉES'],
    ['Services Up','الخدمات العاملة','Services actifs'],['Core Services','الخدمات الأساسية','Services principaux'],['Services Down','الخدمات المتوقفة','Services indisponibles'],['Control Room','غرفة التحكم','Régie'],['Core Service Status','حالة الخدمات الأساسية','État des services principaux'],['Safety Envelope','نطاق الأمان','Périmètre de sécurité'],['Safety','الأمان','Sécurité'],['Readiness','الجاهزية','Préparation'],['Broadcast Modules','وحدات البث','Modules de diffusion'],['Infrastructure','البنية التحتية','Infrastructure'],['Broadcast State','حالة البث','État de diffusion'],['Overall','الحالة العامة','Global'],
    ['Operator Session','جلسة المشغّل','Session opérateur'],['Operator JWT','رمز JWT للمشغّل','JWT opérateur'],['Start Operator Session','بدء جلسة المشغّل','Démarrer la session opérateur'],['Check Session','فحص الجلسة','Vérifier la session'],['Clear Session','مسح الجلسة','Effacer la session'],['Connect','اتصال','Connexion'],['Clear','مسح','Effacer'],['Refresh','تحديث','Actualiser'],['Refresh Health','تحديث الصحة','Actualiser l’état'],['Refresh now','تحديث الآن','Actualiser maintenant'],['Back to Dashboard','العودة إلى لوحة التحكم','Retour au tableau de bord'],['Dashboard','لوحة التحكم','Tableau de bord'],
    ['Connected','متصل','Connecté'],['Disconnected','غير متصل','Déconnecté'],['Waiting…','بانتظار…','En attente…'],['Loading…','جارٍ التحميل…','Chargement…'],['No data','لا توجد بيانات','Aucune donnée'],['No session checked.','لم يتم فحص أي جلسة.','Aucune session vérifiée.'],['JWT required','رمز JWT مطلوب','JWT requis'],['Operator JWT required','رمز JWT للمشغّل مطلوب','JWT opérateur requis'],
    ['READY','جاهز','PRÊT'],['UNAVAILABLE','غير متاح','INDISPONIBLE'],['UNKNOWN','غير معروف','INCONNU'],['UP','يعمل','ACTIF'],['DOWN','متوقف','HORS SERVICE'],['OFF','متوقف','ARRÊT'],['ON','يعمل','ACTIF'],['SAFE','آمن','SÛR'],['UNSAFE','غير آمن','NON SÛR'],['BLOCKED','محظور','BLOQUÉ'],['LOCKED','مقفل','VERROUILLÉ'],['HEALTHY','سليم','SAIN'],['UNHEALTHY','غير سليم','DÉFAILLANT'],['DEGRADED','متدهور','DÉGRADÉ'],['CRITICAL','حرج','CRITIQUE'],['ACTIVE','نشط','ACTIF'],['IDLE','خامل','INACTIF'],['STALE','قديم','PÉRIMÉ'],['ERROR','خطأ','ERREUR'],['RUNNING','قيد التشغيل','EN COURS'],['STOPPED','متوقف','ARRÊTÉ'],['STOPPING','جارٍ الإيقاف','ARRÊT EN COURS'],['STARTING','جارٍ البدء','DÉMARRAGE'],['RECOVERING','جارٍ الاستعادة','RÉCUPÉRATION'],['FAILED','فشل','ÉCHEC'],['ASSIGNED','مُعيَّن','ASSIGNÉ'],['STANDBY','استعداد','VEILLE'],['CONNECTING','جارٍ الاتصال','CONNEXION'],['DISCONNECTING','جارٍ قطع الاتصال','DÉCONNEXION'],
    ['Channel','القناة','Chaîne'],['Selected Channel','القناة المحددة','Chaîne sélectionnée'],['Channel Runtimes','تشغيل القنوات','Exécutions des chaînes'],['Runtime','التشغيل','Exécution'],['Runtime State Machine','آلة حالات التشغيل','Machine d’état d’exécution'],['Runtime Initialization','تهيئة التشغيل','Initialisation de l’exécution'],['Source Mode','وضع المصدر','Mode source'],['Generation','الجيل','Génération'],['Service Runtime','تشغيل الخدمة','Exécution du service'],['Recent Transitions','الانتقالات الأخيرة','Transitions récentes'],['Transition Reason','سبب الانتقال','Motif de transition'],
    ['Create Channel','إنشاء قناة','Créer une chaîne'],['Slug','المعرّف المختصر','Identifiant court'],['Name','الاسم','Nom'],['Timezone','المنطقة الزمنية','Fuseau horaire'],['Session Title','عنوان الجلسة','Titre de session'],['Broadcast Session','جلسة البث','Session de diffusion'],['Create Session Record','إنشاء سجل جلسة','Créer l’enregistrement de session'],
    ['Programs','البرامج','Programmes'],['Episodes','الحلقات','Épisodes'],['Playlists','قوائم التشغيل','Listes de lecture'],['Rundowns','قوائم البث','Conducteurs'],['Schedule','الجدول','Planning'],['Schedule Timeline','الخط الزمني للجدول','Chronologie du planning'],['Schedule Slots','فترات الجدول','Créneaux du planning'],['EPG Events','أحداث EPG','Événements EPG'],['Create Program','إنشاء برنامج','Créer un programme'],['Create Playlist','إنشاء قائمة تشغيل','Créer une liste de lecture'],['Create Rundown','إنشاء قائمة بث','Créer un conducteur'],['Create Schedule Slot','إنشاء فترة جدول','Créer un créneau'],['Program title','عنوان البرنامج','Titre du programme'],['Episode title','عنوان الحلقة','Titre de l’épisode'],['Playlist name','اسم قائمة التشغيل','Nom de la liste'],['Daily rundown','قائمة البث اليومية','Conducteur quotidien'],['Category','الفئة','Catégorie'],['Priority','الأولوية','Priorité'],['Start','البداية','Début'],['End','النهاية','Fin'],['Validate & Create Slot','تحقق وأنشئ الفترة','Valider et créer le créneau'],
    ['Assets','الأصول','Ressources'],['Asset','الأصل','Ressource'],['Selected Asset','الأصل المحدد','Ressource sélectionnée'],['Register Asset','تسجيل أصل','Enregistrer une ressource'],['Media type','نوع الوسائط','Type de média'],['File','الملف','Fichier'],['Status','الحالة','État'],['Size','الحجم','Taille'],['Type','النوع','Type'],['Duration ms','المدة بالمللي ثانية','Durée ms'],['Metadata JSON','بيانات وصفية JSON','Métadonnées JSON'],['Save metadata','حفظ البيانات الوصفية','Enregistrer les métadonnées'],['Presigned PUT URL','رابط PUT موقّع مسبقًا','URL PUT présignée'],['Temporary download','تنزيل مؤقت','Téléchargement temporaire'],['Upload','رفع','Téléverser'],['Upload through staging relay','رفع عبر وسيط بيئة الاختبار','Téléverser via le relais de préproduction'],['Verify external/presigned upload','التحقق من الرفع الخارجي/الموقّع','Vérifier le téléversement externe/présigné'],
    ['Compile Rundown','تجميع قائمة البث','Compiler le conducteur'],['Refresh Runs','تحديث عمليات التشغيل','Actualiser les exécutions'],['Runs','عمليات التشغيل','Exécutions'],['Selected Run','عملية التشغيل المحددة','Exécution sélectionnée'],['Fallback Preview','معاينة المصدر الاحتياطي','Aperçu de secours'],['Resolve','حل','Résoudre'],['Ready','جاهز','Prêt'],['Pause','إيقاف مؤقت','Pause'],['Complete','إكمال','Terminer'],['Cancel','إلغاء','Annuler'],
    ['Create Room','إنشاء غرفة','Créer une salle'],['Rooms','الغرف','Salles'],['Room','الغرفة','Salle'],['Room Lifecycle','دورة حياة الغرفة','Cycle de vie de la salle'],['Participants','المشاركون','Participants'],['Participant name','اسم المشارك','Nom du participant'],['Scenes','المشاهد','Scènes'],['Scene name','اسم المشهد','Nom de la scène'],['Preview / Program','المعاينة / البرنامج','Prévisualisation / Programme'],['TAKE PREVIEW → PROGRAM','نقل المعاينة ← البرنامج','BASCULER PRÉVISUALISATION → PROGRAMME'],['PREVIEW','معاينة','PRÉVISUALISATION'],['PROGRAM','البرنامج','PROGRAMME'],['Waiting','بانتظار','En attente'],['Go Live (Studio State)','بدء البث (حالة الاستوديو)','Passer en direct (état studio)'],['Archive','أرشفة','Archiver'],
    ['WebRTC Media Session Lab','مختبر جلسة وسائط WebRTC','Laboratoire de session média WebRTC'],['Check Safety','فحص الأمان','Vérifier la sécurité'],['Load Rooms','تحميل الغرف','Charger les salles'],['Select studio room','اختر غرفة الاستوديو','Sélectionner une salle studio'],['Open Media Session','فتح جلسة وسائط','Ouvrir une session média'],['Camera','الكاميرا','Caméra'],['Microphone','الميكروفون','Microphone'],['Screen','الشاشة','Écran'],['Start Camera + Mic','تشغيل الكاميرا + الميكروفون','Démarrer caméra + micro'],['Share Screen','مشاركة الشاشة','Partager l’écran'],['Stop Screen','إيقاف مشاركة الشاشة','Arrêter le partage'],['Stop All Media','إيقاف كل الوسائط','Arrêter tous les médias'],['Start WebRTC Loopback','بدء حلقة WebRTC المحلية','Démarrer la boucle WebRTC'],['Local Capture','التقاط محلي','Capture locale'],['WebRTC Loopback Receiver','مستقبل حلقة WebRTC','Récepteur de boucle WebRTC'],['Session / Track Registry','سجل الجلسة / المسارات','Registre session / pistes'],
    ['Monitoring Targets','أهداف المراقبة','Cibles de supervision'],['Create Monitoring Target','إنشاء هدف مراقبة','Créer une cible de supervision'],['Selected Target Sample','عينة الهدف المحدد','Échantillon de la cible sélectionnée'],['Active Alerts','التنبيهات النشطة','Alertes actives'],['Open Alerts','التنبيهات المفتوحة','Alertes ouvertes'],['Incidents','الحوادث','Incidents'],['Create Incident','إنشاء حادث','Créer un incident'],['Severity','الخطورة','Sévérité'],['Summary','الملخص','Résumé'],['Open Incident','فتح حادث','Ouvrir l’incident'],['Redundancy Group','مجموعة التكرار','Groupe de redondance'],['Redundancy Groups','مجموعات التكرار','Groupes de redondance'],['Create Group','إنشاء مجموعة','Créer un groupe'],['Members','الأعضاء','Membres'],['Current Health','الصحة الحالية','État actuel'],['Recent Decisions','القرارات الأخيرة','Décisions récentes'],['Selected Group','المجموعة المحددة','Groupe sélectionné'],['Policy','السياسة','Politique'],['Evaluate','تقييم','Évaluer'],['Evaluate Failover','تقييم التحويل الاحتياطي','Évaluer le basculement'],['Reload Decisions','إعادة تحميل القرارات','Recharger les décisions'],['Recommendations','التوصيات','Recommandations'],['Authorized','المصرّح بها','Autorisées'],['Authorize Record','تسجيل التصريح','Enregistrer l’autorisation'],
    ['Register Encoder Node','تسجيل عقدة ترميز','Enregistrer un nœud encodeur'],['Node Key','مفتاح العقدة','Clé du nœud'],['Display Name','الاسم المعروض','Nom affiché'],['Zone','المنطقة','Zone'],['Register / Heartbeat','تسجيل / نبضة حياة','Enregistrer / Heartbeat'],['Nodes','العقد','Nœuds'],['Jobs','المهام','Tâches'],['Selected Job','المهمة المحددة','Tâche sélectionnée'],['Create Encoder Job','إنشاء مهمة ترميز','Créer une tâche d’encodage'],['Playout Run ID (optional)','معرّف تشغيل Playout (اختياري)','ID d’exécution Playout (optionnel)'],['Profile','الملف التعريفي','Profil'],['Requested Outputs (intent only)','المخرجات المطلوبة (نية فقط)','Sorties demandées (intention uniquement)'],['Create Job Intent','إنشاء نية المهمة','Créer l’intention de tâche'],['Encoder Node','عقدة الترميز','Nœud encodeur'],['Select node','اختر عقدة','Sélectionner un nœud'],['Assign Node','تعيين العقدة','Assigner le nœud'],['Job State Machine','آلة حالات المهمة','Machine d’état de tâche'],['Encoder Jobs','مهام الترميز','Tâches d’encodage'],['Node State','حالة العقدة','État du nœud'],
    ['Destinations','الوجهات','Destinations'],['Sessions','الجلسات','Sessions'],['Selected Session','الجلسة المحددة','Session sélectionnée'],['Create Destination','إنشاء وجهة','Créer une destination'],['Code','الرمز','Code'],['Kind','النوع','Type'],['Config JSON','إعدادات JSON','Configuration JSON'],['Create Disabled Destination','إنشاء وجهة معطلة','Créer une destination désactivée'],['Create Output Session','إنشاء جلسة إخراج','Créer une session de sortie'],['Encoder Job','مهمة الترميز','Tâche d’encodage'],['Destination','الوجهة','Destination'],['Output Sessions','جلسات الإخراج','Sessions de sortie'],['Selected Session State','حالة الجلسة المحددة','État de la session sélectionnée'],
    ['Upsert Manifest','إنشاء/تحديث Manifest','Créer/mettre à jour le manifeste'],['Variant','النسخة','Variante'],['Path','المسار','Chemin'],['Target duration','المدة المستهدفة','Durée cible'],['Playlist window','نافذة قائمة التشغيل','Fenêtre de playlist'],['Save Manifest','حفظ Manifest','Enregistrer le manifeste'],['Manifests','ملفات Manifest','Manifestes'],['Selected','المحدد','Sélectionné'],['State','الحالة','État'],['HLS Manifests','ملفات HLS Manifest','Manifestes HLS'],['Manifest State','حالة Manifest','État du manifeste'],['M3U Preview','معاينة M3U','Aperçu M3U'],['Generate Preview','إنشاء معاينة','Générer l’aperçu'],
    ['Operator Message','رسالة المشغّل','Message opérateur'],['Connect to begin.','اتصل للبدء.','Connectez-vous pour commencer.'],['Connect first','اتصل أولًا','Connectez-vous d’abord'],['Select a channel.','اختر قناة.','Sélectionnez une chaîne.'],['Select a channel first','اختر قناة أولًا','Sélectionnez d’abord une chaîne'],['Select a program.','اختر برنامجًا.','Sélectionnez un programme.'],['Select a node first','اختر عقدة أولًا','Sélectionnez d’abord un nœud'],['Select a manifest first','اختر Manifest أولًا','Sélectionnez d’abord un manifeste'],['No channels.','لا توجد قنوات.','Aucune chaîne.'],['No programs.','لا توجد برامج.','Aucun programme.'],['No playlists.','لا توجد قوائم تشغيل.','Aucune liste de lecture.'],['No rundowns.','لا توجد قوائم بث.','Aucun conducteur.'],['No schedule slots.','لا توجد فترات جدول.','Aucun créneau.'],['No assets.','لا توجد أصول.','Aucune ressource.'],['No runs.','لا توجد عمليات تشغيل.','Aucune exécution.'],['No encoder nodes.','لا توجد عقد ترميز.','Aucun nœud encodeur.'],['No destinations.','لا توجد وجهات.','Aucune destination.'],['No output sessions.','لا توجد جلسات إخراج.','Aucune session de sortie.'],['No manifests.','لا توجد ملفات Manifest.','Aucun manifeste.'],['No redundancy groups.','لا توجد مجموعات تكرار.','Aucun groupe de redondance.'],['No members.','لا يوجد أعضاء.','Aucun membre.'],['No health data.','لا توجد بيانات صحة.','Aucune donnée d’état.'],['No decisions yet.','لا توجد قرارات بعد.','Aucune décision pour le moment.'],['No transitions.','لا توجد انتقالات.','Aucune transition.'],['No channel selected.','لم يتم اختيار قناة.','Aucune chaîne sélectionnée.'],['No group selected.','لم يتم اختيار مجموعة.','Aucun groupe sélectionné.'],['No room selected.','لم يتم اختيار غرفة.','Aucune salle sélectionnée.'],['No run selected.','لم يتم اختيار عملية تشغيل.','Aucune exécution sélectionnée.'],['No media session.','لا توجد جلسة وسائط.','Aucune session média.'],
    ['Production outputs disabled','مخرجات الإنتاج معطلة','Sorties de production désactivées'],['No live production switching in staging.','لا يوجد تحويل مباشر للإنتاج في بيئة الاختبار.','Aucun basculement de production en direct en préproduction.'],['CONTROL PLANE READY','طبقة التحكم جاهزة','PLAN DE CONTRÔLE PRÊT'],['STAGING LOCKED','بيئة الاختبار مقفلة','PRÉPRODUCTION VERROUILLÉE'],['OUTPUTS DISABLED','المخرجات معطلة','SORTIES DÉSACTIVÉES'],['OUTPUTS OFF','المخرجات متوقفة','SORTIES ARRÊTÉES'],['DECISION ONLY','قرار فقط','DÉCISION UNIQUEMENT']
  ].forEach(x=>add(...x));

  const lex={
    ar:{'Broadcast Nexus':'منظومة البث','staging':'بيئة الاختبار','production':'الإنتاج','control plane':'طبقة التحكم','operator':'المشغّل','session':'جلسة','channel':'قناة','channels':'قنوات','room':'غرفة','rooms':'غرف','program':'برنامج','programs':'برامج','episode':'حلقة','episodes':'حلقات','playlist':'قائمة تشغيل','playlists':'قوائم تشغيل','rundown':'قائمة بث','rundowns':'قوائم بث','schedule':'جدول','scheduler':'الجدولة','media':'وسائط','asset':'أصل','assets':'أصول','encoder':'المُرمِّز','distribution':'التوزيع','destination':'وجهة','destinations':'وجهات','output':'إخراج','outputs':'مخرجات','monitoring':'مراقبة','incident':'حادث','incidents':'حوادث','alert':'تنبيه','alerts':'تنبيهات','health':'صحة','safety':'أمان','state':'حالة','status':'حالة','selected':'محدد','select':'اختر','create':'إنشاء','register':'تسجيل','refresh':'تحديث','load':'تحميل','save':'حفظ','clear':'مسح','connect':'اتصال','connected':'متصل','disconnected':'غير متصل','start':'بدء','stop':'إيقاف','pause':'إيقاف مؤقت','complete':'إكمال','cancel':'إلغاء','evaluate':'تقييم','authorize':'تصريح','enabled':'مفعّل','disabled':'معطّل','ready':'جاهز','running':'قيد التشغيل','failed':'فشل','error':'خطأ','unknown':'غير معروف','safe':'آمن','blocked':'محظور','active':'نشط','inactive':'غير نشط','optional':'اختياري','required':'مطلوب','title':'العنوان','name':'الاسم','type':'النوع','mode':'الوضع','source':'المصدر','priority':'الأولوية','current':'الحالي','recent':'الأخيرة','message':'رسالة','preview':'معاينة','screen':'الشاشة','camera':'الكاميرا','microphone':'الميكروفون','participant':'مشارك','participants':'المشاركون','scene':'مشهد','scenes':'مشاهد','node':'عقدة','nodes':'عقد','job':'مهمة','jobs':'مهام','manifest':'Manifest','manifests':'ملفات Manifest','group':'مجموعة','groups':'مجموعات','member':'عضو','members':'أعضاء','policy':'سياسة','decision':'قرار','decisions':'قرارات','recommendations':'توصيات','authorized':'مصرّح','only':'فقط','no':'لا','none':'لا شيء'},
    fr:{'Broadcast Nexus':'Broadcast Nexus','staging':'préproduction','production':'production','control plane':'plan de contrôle','operator':'opérateur','session':'session','channel':'chaîne','channels':'chaînes','room':'salle','rooms':'salles','program':'programme','programs':'programmes','episode':'épisode','episodes':'épisodes','playlist':'liste de lecture','playlists':'listes de lecture','rundown':'conducteur','rundowns':'conducteurs','schedule':'planning','scheduler':'planificateur','media':'média','asset':'ressource','assets':'ressources','encoder':'encodeur','distribution':'distribution','destination':'destination','destinations':'destinations','output':'sortie','outputs':'sorties','monitoring':'supervision','incident':'incident','incidents':'incidents','alert':'alerte','alerts':'alertes','health':'état','safety':'sécurité','state':'état','status':'état','selected':'sélectionné','select':'sélectionner','create':'créer','register':'enregistrer','refresh':'actualiser','load':'charger','save':'enregistrer','clear':'effacer','connect':'connexion','connected':'connecté','disconnected':'déconnecté','start':'démarrer','stop':'arrêter','pause':'pause','complete':'terminer','cancel':'annuler','evaluate':'évaluer','authorize':'autoriser','enabled':'activé','disabled':'désactivé','ready':'prêt','running':'en cours','failed':'échec','error':'erreur','unknown':'inconnu','safe':'sûr','blocked':'bloqué','active':'actif','inactive':'inactif','optional':'optionnel','required':'requis','title':'titre','name':'nom','type':'type','mode':'mode','source':'source','priority':'priorité','current':'actuel','recent':'récent','message':'message','preview':'aperçu','screen':'écran','camera':'caméra','microphone':'microphone','participant':'participant','participants':'participants','scene':'scène','scenes':'scènes','node':'nœud','nodes':'nœuds','job':'tâche','jobs':'tâches','manifest':'manifeste','manifests':'manifestes','group':'groupe','groups':'groupes','member':'membre','members':'membres','policy':'politique','decision':'décision','decisions':'décisions','recommendations':'recommandations','authorized':'autorisé','only':'uniquement','no':'aucun','none':'aucun'}
  };

  const originals=new WeakMap();
  const attrOriginals=new WeakMap();
  const titleOriginal=document.title;
  const escRe=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
  function loose(value,lang){
    let out=value;
    const entries=Object.entries(lex[lang]||{}).sort((a,b)=>b[0].length-a[0].length);
    for(const [from,to] of entries){
      const re=new RegExp(`\\b${escRe(from)}\\b`,'gi');
      out=out.replace(re,to);
    }
    return out;
  }
  function t(value,lang){
    if(!value||lang==='en')return value;
    return exact[lang]?.[value]||loose(value,lang);
  }
  function translateAttrs(el,lang){
    let store=attrOriginals.get(el);if(!store){store={};attrOriginals.set(el,store)}
    ['placeholder','title','aria-label'].forEach(attr=>{
      if(!el.hasAttribute(attr))return;
      if(!(attr in store))store[attr]=el.getAttribute(attr)||'';
      el.setAttribute(attr,t(store[attr],lang));
    });
  }
  function translateNode(node,lang){
    if(node.nodeType===Node.TEXT_NODE){
      const parent=node.parentElement;
      if(parent&&skipTags.has(parent.tagName))return;
      const raw=node.nodeValue;if(!raw||!raw.trim())return;
      if(!originals.has(node))originals.set(node,raw);
      const base=originals.get(node),trimmed=base.trim();
      node.nodeValue=base.replace(trimmed,t(trimmed,lang));return;
    }
    if(node.nodeType!==Node.ELEMENT_NODE||skipTags.has(node.tagName)||node.dataset?.i18nSkip==='true')return;
    if(node.tagName==='OPTION'&&!node.hasAttribute('value'))node.setAttribute('value',node.value);
    translateAttrs(node,lang);
    [...node.childNodes].forEach(c=>translateNode(c,lang));
  }
  function apply(lang){
    if(!supported.includes(lang))lang='ar';
    localStorage.setItem(STORAGE_KEY,lang);
    document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
    document.body?.classList.toggle('iuoamc-rtl',lang==='ar');
    document.title=t(titleOriginal,lang);
    translateNode(document.body,lang);
    document.querySelectorAll('[data-lang-choice]').forEach(b=>b.classList.toggle('active',b.dataset.langChoice===lang));
    window.dispatchEvent(new CustomEvent('iuoamc:language',{detail:{lang}}));
  }
  function addSwitcher(){
    if(document.getElementById('iuoamcLanguageSwitcher'))return;
    const style=document.createElement('style');
    style.textContent=`#iuoamcLanguageSwitcher{position:fixed;z-index:99999;top:12px;right:14px;display:flex;gap:5px;padding:5px;border:1px solid rgba(214,170,75,.3);background:rgba(7,17,31,.96);border-radius:12px;box-shadow:0 8px 30px rgba(0,0,0,.25);direction:ltr}#iuoamcLanguageSwitcher button{border:1px solid #263a5a;background:#0d1a2d;color:#b9c7db;border-radius:8px;padding:6px 9px;font:600 11px/1 system-ui;cursor:pointer}#iuoamcLanguageSwitcher button.active{color:#f3cc76;border-color:rgba(214,170,75,.7);background:#18253a}.iuoamc-rtl body,.iuoamc-rtl .main,.iuoamc-rtl .card,.iuoamc-rtl .sidebar,.iuoamc-rtl .wrap,.iuoamc-rtl .side{text-align:right}.iuoamc-rtl .sidebar,.iuoamc-rtl .side{border-right:0!important;border-left:1px solid var(--line,#20324f)}.iuoamc-rtl .top,.iuoamc-rtl .topbar,.iuoamc-rtl .toolbar,.iuoamc-rtl .row{direction:rtl}.iuoamc-rtl input,.iuoamc-rtl textarea,.iuoamc-rtl select{text-align:right}@media(max-width:680px){#iuoamcLanguageSwitcher{top:auto;bottom:12px;right:12px}}`;
    document.head.appendChild(style);
    const box=document.createElement('div');box.id='iuoamcLanguageSwitcher';box.setAttribute('aria-label','Language');box.dataset.i18nSkip='true';
    [['ar','العربية'],['en','English'],['fr','Français']].forEach(([code,label])=>{const b=document.createElement('button');b.type='button';b.dataset.langChoice=code;b.textContent=label;b.onclick=()=>apply(code);box.appendChild(b)});
    document.body.appendChild(box);
  }
  document.addEventListener('DOMContentLoaded',()=>{
    addSwitcher();apply(localStorage.getItem(STORAGE_KEY)||'ar');
    const obs=new MutationObserver(m=>{const lang=localStorage.getItem(STORAGE_KEY)||'ar';m.forEach(x=>x.addedNodes.forEach(n=>translateNode(n,lang)))});
    obs.observe(document.body,{childList:true,subtree:true});
  });
  window.IUOAMCI18N={setLanguage:apply,getLanguage:()=>localStorage.getItem(STORAGE_KEY)||'ar',translate:(s,lang)=>t(s,lang||localStorage.getItem(STORAGE_KEY)||'ar')};
})();
