@extends('layouts.control')
@section('title', __('memberships.catalog_settings'))
@section('content')
<div class="membership-module">
    <section class="page-heading"><div><span class="eyebrow">IUOAMC / MEMBERSHIP SETTINGS</span><h1>{{ __('memberships.catalog_settings') }}</h1><p>{{ __('memberships.catalog_settings_lead') }}</p></div><a class="secondary-action" href="{{ route('memberships.index',['locale'=>app()->getLocale()]) }}">{{ __('memberships.back') }}</a></section>
    @if(session('success'))<div class="alert">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-error" role="alert">{{ $errors->first() }}</div>@endif

    <section class="form-card"><header><div><h2>{{ __('memberships.professional_titles') }}</h2><p>{{ __('memberships.catalog_history_notice') }}</p></div></header>
        @foreach($titles as $title)<form class="institutional-form" method="post" action="{{ route('memberships.settings.titles.update',['locale'=>app()->getLocale(),'title'=>$title->id]) }}">@csrf @method('put')
            <div class="form-grid two-columns"><label class="field"><span>AR</span><input name="name_ar" required value="{{ $title->name_ar }}"></label><label class="field"><span>EN</span><input name="name_en" required value="{{ $title->name_en }}"></label><label class="field"><span>FR</span><input name="name_fr" required value="{{ $title->name_fr }}"></label><label class="field"><span>{{ __('memberships.sort_order') }}</span><input type="number" name="sort_order" min="0" max="9999" required value="{{ $title->sort_order }}"></label></div>
            <label><input type="checkbox" name="is_active" value="1" @checked($title->is_active)> {{ __('memberships.active_option') }}</label> <button class="secondary-action" type="submit">{{ __('memberships.save') }}</button>
        </form>@endforeach
        <form class="institutional-form" method="post" action="{{ route('memberships.settings.titles.store',['locale'=>app()->getLocale()]) }}">@csrf<h3>{{ __('memberships.add_professional_title') }}</h3><div class="form-grid two-columns"><label class="field"><span>AR</span><input name="name_ar" required></label><label class="field"><span>EN</span><input name="name_en" required></label><label class="field"><span>FR</span><input name="name_fr" required></label><label class="field"><span>{{ __('memberships.sort_order') }}</span><input type="number" name="sort_order" min="0" max="9999" value="100" required></label></div><input type="hidden" name="is_active" value="1"><button class="primary-action" type="submit">{{ __('memberships.add') }}</button></form>
    </section>

    <section class="form-card"><header><div><h2>{{ __('memberships.subscription_plans') }}</h2></div></header>
        @foreach($plans as $plan)<form class="institutional-form" method="post" action="{{ route('memberships.settings.plans.update',['locale'=>app()->getLocale(),'plan'=>$plan->id]) }}">@csrf @method('put')<div class="form-grid two-columns"><label class="field"><span>{{ __('memberships.years_count') }}</span><input type="number" name="years" min="1" max="50" required value="{{ $plan->years }}"></label><label class="field"><span>{{ __('memberships.fee_gbp') }}</span><input type="number" step="0.01" name="fee_amount" required value="{{ number_format($plan->fee_pence/100,2,'.','') }}"></label><label class="field"><span>{{ __('memberships.sort_order') }}</span><input type="number" name="sort_order" required value="{{ $plan->sort_order }}"></label></div><label><input type="checkbox" name="is_active" value="1" @checked($plan->is_active)> {{ __('memberships.active_option') }}</label> <button class="secondary-action" type="submit">{{ __('memberships.save') }}</button></form>@endforeach
        <form class="institutional-form" method="post" action="{{ route('memberships.settings.plans.store',['locale'=>app()->getLocale()]) }}">@csrf<h3>{{ __('memberships.add_subscription_plan') }}</h3><div class="form-grid two-columns"><label class="field"><span>{{ __('memberships.years_count') }}</span><input type="number" name="years" min="1" max="50" required></label><label class="field"><span>{{ __('memberships.fee_gbp') }}</span><input type="number" step="0.01" name="fee_amount" min="0" required></label><label class="field"><span>{{ __('memberships.sort_order') }}</span><input type="number" name="sort_order" value="100" required></label></div><input type="hidden" name="is_active" value="1"><button class="primary-action" type="submit">{{ __('memberships.add') }}</button></form>
    </section>

    <section class="form-card"><header><div><h2>{{ __('memberships.payment_methods') }}</h2><p>{{ __('memberships.payment_settings_notice') }}</p></div></header>
        @foreach($paymentMethods as $method)<form class="institutional-form" method="post" action="{{ route('memberships.settings.payments.update',['locale'=>app()->getLocale(),'paymentMethod'=>$method->id]) }}">@csrf @method('put')<div class="form-grid two-columns"><label class="field"><span>AR</span><input name="name_ar" required value="{{ $method->name_ar }}"></label><label class="field"><span>EN</span><input name="name_en" required value="{{ $method->name_en }}"></label><label class="field"><span>FR</span><input name="name_fr" required value="{{ $method->name_fr }}"></label><label class="field"><span>{{ __('memberships.sort_order') }}</span><input type="number" name="sort_order" required value="{{ $method->sort_order }}"></label></div><label><input type="checkbox" name="requires_waiver_reason" value="1" @checked($method->requires_waiver_reason)> {{ __('memberships.requires_waiver_reason') }}</label> <label><input type="checkbox" name="is_active" value="1" @checked($method->is_active)> {{ __('memberships.active_option') }}</label> <button class="secondary-action" type="submit">{{ __('memberships.save') }}</button></form>@endforeach
        <form class="institutional-form" method="post" action="{{ route('memberships.settings.payments.store',['locale'=>app()->getLocale()]) }}">@csrf<h3>{{ __('memberships.add_payment_method') }}</h3><div class="form-grid two-columns"><label class="field"><span>AR</span><input name="name_ar" required></label><label class="field"><span>EN</span><input name="name_en" required></label><label class="field"><span>FR</span><input name="name_fr" required></label><label class="field"><span>{{ __('memberships.sort_order') }}</span><input type="number" name="sort_order" value="100" required></label></div><label><input type="checkbox" name="requires_waiver_reason" value="1"> {{ __('memberships.requires_waiver_reason') }}</label><input type="hidden" name="is_active" value="1"><button class="primary-action" type="submit">{{ __('memberships.add') }}</button></form>
    </section>
</div>
@endsection
