@extends('layouts.control')
@section('title', $section->exists ? __('journal.edit_section') : __('journal.add_section'))
@push('styles')<link rel="stylesheet" href="{{ asset('assets/css/iuoamc-journal-1.0.0.css') }}">@endpush
@section('content')<div class="journal-control">@include('control.journal._nav')
<section class="page-heading"><div><span class="eyebrow">MCIJ / TAXONOMY</span><h1>{{ $section->exists ? __('journal.edit_section') : __('journal.add_section') }}</h1><p>{{ __('journal.section_form_intro') }}</p></div></section>
@if($errors->any())<div class="alert alert-error">{{ $errors->first() }}</div>@endif
<section class="form-card"><form class="journal-stack-form" method="post" action="{{ $section->exists ? route('journal.control.sections.update',['locale'=>app()->getLocale(),'section'=>$section]) : route('journal.control.sections.store',['locale'=>app()->getLocale()]) }}">@csrf @if($section->exists)@method('put')@endif
<div class="journal-form-grid"><label>Slug<input name="slug" dir="ltr" required maxlength="100" value="{{ old('slug',$section->slug) }}"></label><label>{{ __('journal.scope') }}<select name="scope">@foreach(\App\Models\JournalSection::SCOPES as $scope)<option value="{{ $scope }}" @selected(old('scope',$section->scope?:'all')===$scope)>{{ __('journal.section_scopes.'.$scope) }}</option>@endforeach</select></label><label>{{ __('journal.status') }}<select name="status">@foreach(['active','inactive'] as $status)<option value="{{ $status }}" @selected(old('status',$section->status?:'active')===$status)>{{ __('journal.section_statuses.'.$status) }}</option>@endforeach</select></label><label>{{ __('journal.sort_order') }}<input type="number" min="1" max="1000" name="sort_order" value="{{ old('sort_order',$section->sort_order?:100) }}"></label></div>
@foreach(['ar'=>'العربية','en'=>'English','fr'=>'Français'] as $language=>$label)<fieldset><legend>{{ $label }}</legend><label>{{ __('journal.name') }}<input name="name[{{ $language }}]" required maxlength="180" value="{{ old('name.'.$language,($section->name??[])[$language]??'') }}"></label><label>{{ __('journal.description') }}<textarea name="description[{{ $language }}]" maxlength="500">{{ old('description.'.$language,($section->description??[])[$language]??'') }}</textarea></label></fieldset>@endforeach
<button class="primary-action">{{ __('journal.save_section') }}</button></form></section></div>@endsection
