<?php
return [
    'secure_portal'=>'بوابة الحساب الآمنة','secure_portal_intro'=>'وصول موثّق إلى بياناتك وعضوياتك ومستنداتك فقط.','account_reference'=>'رقم المستخدم',
    'navigation'=>'تنقل الحساب','my_account'=>'حسابي','my_profile'=>'ملفي الشخصي','control_center'=>'لوحة الإدارة','logout'=>'تسجيل الخروج',
    'welcome'=>'مرحبًا، :name','dashboard_intro'=>'كل عضوياتك وشهاداتك ومستنداتك المرتبطة ببريدك الموثّق في مكان آمن واحد.','refresh_records'=>'تحديث سجلاتي','records_refreshed'=>'تم تحديث السجلات المرتبطة ببريدك.','verified_email'=>'البريد موثّق','name'=>'الاسم','email'=>'البريد الإلكتروني','email_locked'=>'تغيير البريد يحتاج إلى تحقق أمني منفصل.','language'=>'اللغة','save'=>'حفظ','profile_saved'=>'تم حفظ الملف الشخصي.',
    'memberships'=>'عضوياتي','certificates'=>'شهاداتي','documents'=>'مستنداتي','documents_invoices_receipts'=>'المستندات والفواتير والإيصالات','new_application'=>'طلب عضوية جديد','apply_membership'=>'طلب عضوية','no_memberships'=>'لا توجد عضوية مرتبطة بهذا البريد حتى الآن.','no_certificates'=>'لا توجد شهادة صادرة مرتبطة بهذا البريد حتى الآن.','no_documents'=>'لا توجد مستندات أو فواتير أو إيصالات مرتبطة بهذا البريد.','download_pdf'=>'تحميل PDF','download_card'=>'تحميل البطاقة','download_membership_certificate'=>'تحميل شهادة العضوية','integrity_blocked'=>'أوقف التنزيل لحين فحص سلامة السجل.',
    'create_account'=>'فتح حساب','register_intro'=>'أنشئ حسابًا ببريدك الحقيقي للوصول إلى سجلاتك وطلباتك فقط.','password'=>'كلمة المرور','password_confirmation'=>'تأكيد كلمة المرور','password_help'=>'12 حرفًا على الأقل، وتضم أحرفًا كبيرة وصغيرة وأرقامًا.','registration_consent'=>'أوافق على استخدام بياناتي لإنشاء الحساب وربط سجلاتي ببريدي بعد التحقق.','have_account'=>'لدي حساب بالفعل','verify_email'=>'تحقق من بريدك','verify_email_intro'=>'أرسلنا رابط التحقق إلى :email. افتحه لتفعيل الوصول إلى بياناتك.','verification_resent'=>'أُرسل رابط تحقق جديد.','resend_verification'=>'إعادة إرسال رابط التحقق','email_verified'=>'تم توثيق بريدك وربط سجلاتك بأمان.','forgot_password'=>'نسيت كلمة المرور','forgot_intro'=>'أدخل بريد الحساب وسنرسل تعليمات الاستعادة إذا كان الحساب موجودًا.','send_reset'=>'إرسال رابط الاستعادة','back_login'=>'العودة لتسجيل الدخول','reset_password'=>'تعيين كلمة مرور جديدة','reset_sent'=>'إذا كان البريد مسجلًا فستصله تعليمات الاستعادة.',
    'application_intro'=>'أدخل بياناتك وارفع صورة واضحة. يُرسل الطلب إلى الإدارة للمراجعة ولا تتفعّل العضوية تلقائيًا.','membership_details'=>'بيانات العضوية','identity_details'=>'الهوية والصورة','organization'=>'الجهة','choose'=>'اختر','membership_type'=>'نوع العضوية','full_name'=>'الاسم الكامل','latin_name'=>'الاسم باللاتينية','professional_title'=>'الصفة المهنية','country_code'=>'رمز الدولة','phone'=>'الهاتف','private_data'=>'بيانات خاصة لا تظهر للعامة','date_of_birth'=>'تاريخ الميلاد','nationality_code'=>'رمز الجنسية','address'=>'العنوان','city'=>'المدينة','postal_code'=>'الرمز البريدي','residence_country_code'=>'رمز بلد الإقامة','identification_type'=>'نوع وثيقة الهوية','identification_number'=>'رقم وثيقة الهوية','qualifications'=>'المؤهلات والخبرة','photo'=>'الصورة الشخصية','photo_help'=>'JPG أو PNG أو WEBP، واضحة وبحد أقصى 8MB.','consent'=>'أؤكد صحة البيانات وأوافق على معالجتها لمراجعة العضوية وإصدار مستنداتها.','cancel'=>'إلغاء','submit_application'=>'إرسال الطلب للمراجعة','application_submitted'=>'تم إرسال طلب العضوية إلى الإدارة للمراجعة.','duplicate_application'=>'يوجد طلب أو عضوية من هذا النوع لدى الجهة نفسها.',
    'admin_documents'=>'مستندات الحسابات','admin_documents_intro'=>'إصدار ملفات PDF خاصة وربطها ببريد صاحب الحساب.','issue_document'=>'إصدار مستند','issue_document_intro'=>'يُحفظ الملف في التخزين الخاص مع بصمة وسجل تدقيق، ويظهر لصاحب البريد الموثّق فقط.','document_details'=>'بيانات المستند','document_issued'=>'تم إصدار المستند وربطه ببريد المستلم.','category'=>'التصنيف','title'=>'العنوان','recipient_email'=>'بريد المستلم','reference'=>'المرجع','issued_at'=>'تاريخ الإصدار','action'=>'الإجراء','amount'=>'المبلغ','currency'=>'العملة','pdf_file'=>'ملف PDF','no_admin_documents'=>'لم تصدر مستندات حساب بعد.','category_document'=>'مستند','category_invoice'=>'فاتورة','category_receipt'=>'إيصال',
    'status_draft'=>'مسودة','status_pending'=>'قيد المراجعة','status_active'=>'سارية','status_scheduled'=>'مجدولة','status_expired'=>'منتهية','status_suspended'=>'معلّقة','status_rejected'=>'مرفوضة','status_revoked'=>'ملغاة','status_issued'=>'صادرة','status_superseded'=>'مستبدلة',
];
