@extends('layouts.journal')
@section('title', __('journal.track_submission'))
@push('metadata')<meta name="robots" content="noindex,nofollow,noarchive">@endpush
@section('content')
<section class="journal-page-head"><div class="public-container"><span>MCIJ · PRIVATE TRACKING</span><h1>{{ __('journal.track_submission') }}</h1><p>{{ __('journal.tracking_intro') }}</p></div></section>
<div class="public-container journal-tracking">
    @if(session('success'))<div class="journal-form-success" role="status">{{ session('success') }}</div>@endif
    <form method="post" action="{{ route('journal.public.submissions.track',['locale'=>app()->getLocale()]) }}">@csrf<label><span>{{ __('journal.submission_code') }}</span><input dir="ltr" name="submission_code" maxlength="80" required value="{{ old('submission_code') }}"></label><label><span>{{ __('journal.tracking_token') }}</span><input dir="ltr" name="tracking_token" maxlength="64" minlength="64" required></label><button>{{ __('journal.view_status') }}</button></form>
    @if($errors->any() || ($trackingError ?? false))<div class="journal-form-error" role="alert">{{ __('journal.tracking_invalid') }}</div>@endif
    @isset($submission)<section class="journal-tracking-result"><div><span>{{ __('journal.submission_code') }}</span><bdi dir="ltr">{{ $submission->submission_code }}</bdi></div><div><span>{{ __('journal.article_title') }}</span><strong>{{ $submission->title }}</strong></div><div><span>{{ __('journal.status') }}</span><strong>{{ __('journal.submission_statuses.'.$submission->status) }}</strong></div><div><span>{{ __('journal.received') }}</span><time>{{ $submission->received_at->format('Y-m-d H:i') }} UTC</time></div>@if($submission->convertedArticle)<div><span>{{ __('journal.editorial_record') }}</span><bdi dir="ltr">{{ $submission->convertedArticle->article_code }}</bdi></div>@foreach($submission->convertedArticle->decisions as $decision)@if($decision->letter)<article><span>{{ __('journal.decision_letter') }}</span><strong>{{ __('journal.statuses.'.$decision->decision) }}</strong><p>{!! nl2br(e($decision->letter)) !!}</p></article>@endif @endforeach @endif @if($submission->revisions->isNotEmpty())<article><span>{{ __('journal.received_revisions') }}</span><strong>{{ $submission->revisions->count() }}</strong><p>{{ __('journal.latest_revision_received', ['number'=>$submission->revisions->first()->revision_number, 'date'=>$submission->revisions->first()->received_at->format('Y-m-d H:i')]) }}</p></article>@endif</section>
    @if($submission->convertedArticle?->status === 'revision_required')<section class="journal-revision-intake"><h2>{{ __('journal.upload_revision') }}</h2><p>{{ __('journal.upload_revision_help') }}</p><form method="post" enctype="multipart/form-data" action="{{ route('journal.public.submissions.revisions.store',['locale'=>app()->getLocale()]) }}">@csrf<div class="journal-form-grid"><label><span>{{ __('journal.submission_code') }}</span><input dir="ltr" name="submission_code" maxlength="80" required value="{{ $submission->submission_code }}"></label><label><span>{{ __('journal.tracking_token') }}</span><input dir="ltr" name="tracking_token" maxlength="64" minlength="64" required autocomplete="off"></label><label class="wide"><span>{{ __('journal.revised_manuscript') }}</span><input type="file" name="manuscript" accept=".pdf,.doc,.docx" required></label><label class="wide"><span>{{ __('journal.response_letter') }}</span><input type="file" name="response_letter" accept=".pdf,.doc,.docx"></label><label class="wide"><span>{{ __('journal.author_note') }}</span><textarea name="author_note" maxlength="5000" rows="5"></textarea></label></div><button class="journal-submit-button">{{ __('journal.submit_revision') }}</button></form></section>@endif
    @endisset
</div>
@endsection
