@extends('layouts.control')
@section('title', __('journal.submissions'))
@push('styles')<link rel="stylesheet" href="{{ asset('assets/css/iuoamc-journal-1.0.0.css') }}">@endpush
@section('content')
<div class="journal-control">@include('control.journal._nav')
<section class="page-heading"><div><span class="eyebrow">MCIJ / INTAKE</span><h1>{{ __('journal.submissions') }}</h1><p>{{ __('journal.submissions_control_intro') }}</p></div></section>
<div class="journal-stat-grid">@foreach(\App\Models\JournalSubmission::STATUSES as $status)<div><span>{{ __('journal.submission_statuses.'.$status) }}</span><strong>{{ number_format((int)($counts[$status]??0)) }}</strong></div>@endforeach</div>
<section class="data-card"><form class="journal-filter" method="get"><input name="q" value="{{ $filters['q']??'' }}" placeholder="{{ __('journal.search_submission') }}"><select name="status"><option value="">{{ __('journal.all_statuses') }}</option>@foreach(\App\Models\JournalSubmission::STATUSES as $status)<option value="{{ $status }}" @selected(($filters['status']??null)===$status)>{{ __('journal.submission_statuses.'.$status) }}</option>@endforeach</select><select name="type"><option value="">{{ __('journal.all_types') }}</option>@foreach(\App\Models\JournalArticle::TYPES as $type)<option value="{{ $type }}" @selected(($filters['type']??null)===$type)>{{ __('journal.types.'.$type) }}</option>@endforeach</select><button class="secondary-action">{{ __('journal.filter') }}</button></form>
<div class="table-scroll"><table><thead><tr><th>{{ __('journal.submission_code') }}</th><th>{{ __('journal.article_title') }}</th><th>{{ __('journal.author') }}</th><th>{{ __('journal.type') }}</th><th>{{ __('journal.status') }}</th><th>{{ __('journal.received') }}</th><th>{{ __('journal.action') }}</th></tr></thead><tbody>@forelse($submissions as $submission)<tr><td><bdi dir="ltr">{{ $submission->submission_code }}</bdi></td><td>{{ \Illuminate\Support\Str::limit($submission->title,80) }}</td><td>{{ $submission->author_name }}</td><td>{{ __('journal.types.'.$submission->type) }}</td><td><span class="status-badge">{{ __('journal.submission_statuses.'.$submission->status) }}</span></td><td><bdi dir="ltr">{{ $submission->received_at->format('Y-m-d H:i') }}</bdi></td><td><a href="{{ route('journal.control.submissions.show',['locale'=>app()->getLocale(),'submission'=>$submission]) }}">{{ __('journal.open') }}</a></td></tr>@empty<tr><td colspan="7">{{ __('journal.no_submissions') }}</td></tr>@endforelse</tbody></table></div>{{ $submissions->links() }}</section>
</div>
@endsection
