@extends('layouts.control')
@section('title', $submission->title)
@push('styles')<link rel="stylesheet" href="{{ asset('assets/css/iuoamc-journal-1.0.0.css') }}">@endpush
@section('content')
<div class="journal-control">@include('control.journal._nav')
<section class="page-heading"><div><span class="eyebrow"><bdi dir="ltr">{{ $submission->submission_code }}</bdi></span><h1>{{ $submission->title }}</h1><p><span class="journal-type journal-type-{{ $submission->type }}">{{ __('journal.types.'.$submission->type) }}</span> <span class="status-badge">{{ __('journal.submission_statuses.'.$submission->status) }}</span></p></div><div class="heading-actions"><a class="secondary-action" href="{{ route('journal.control.submissions.download',['locale'=>app()->getLocale(),'submission'=>$submission]) }}">{{ __('journal.download_manuscript') }}</a>@if($submission->convertedArticle)<a class="primary-action" href="{{ route('journal.control.articles.show',['locale'=>app()->getLocale(),'article'=>$submission->convertedArticle]) }}">{{ __('journal.open_editorial_record') }}</a>@endif</div></section>
<div class="journal-control-grid"><section class="data-card"><div class="data-card-header"><div><h2>{{ __('journal.submission_details') }}</h2></div></div><dl class="journal-facts"><div><dt>{{ __('journal.author') }}</dt><dd>{{ $submission->author_name }}</dd></div><div><dt>{{ __('journal.author_email') }}</dt><dd><bdi dir="ltr">{{ $submission->author_email }}</bdi></dd></div><div><dt>{{ __('journal.affiliation') }}</dt><dd>{{ $submission->affiliation ?: '—' }}</dd></div><div><dt>ORCID</dt><dd><bdi dir="ltr">{{ $submission->orcid ?: '—' }}</bdi></dd></div><div><dt>{{ __('journal.primary_language') }}</dt><dd>{{ strtoupper($submission->primary_locale) }}</dd></div><div><dt>{{ __('journal.received') }}</dt><dd><bdi dir="ltr">{{ $submission->received_at->format('Y-m-d H:i') }} UTC</bdi></dd></div><div class="wide"><dt>SHA-256</dt><dd><bdi dir="ltr">{{ $submission->file_sha256 }}</bdi></dd></div></dl></section>
<aside class="data-card"><div class="data-card-header"><div><h2>{{ __('journal.intake_actions') }}</h2><p>{{ __('journal.intake_actions_help') }}</p></div></div>@if($submission->status==='submitted')<form class="journal-action" method="post" action="{{ route('journal.control.submissions.screen',['locale'=>app()->getLocale(),'submission'=>$submission]) }}">@csrf<button class="secondary-action">{{ __('journal.begin_screening') }}</button></form>@endif @if(in_array($submission->status,['submitted','screening'],true))<form class="journal-action" method="post" action="{{ route('journal.control.submissions.convert',['locale'=>app()->getLocale(),'submission'=>$submission]) }}">@csrf<button class="primary-action">{{ __('journal.convert_to_editorial_record') }}</button></form><form class="journal-action correction-action" method="post" action="{{ route('journal.control.submissions.decline',['locale'=>app()->getLocale(),'submission'=>$submission]) }}">@csrf<textarea name="reason" required maxlength="5000" placeholder="{{ __('journal.decline_reason') }}"></textarea><button class="secondary-action">{{ __('journal.decline_submission') }}</button></form>@endif</aside></div>
<section class="data-card journal-preview"><div class="data-card-header"><div><h2>{{ __('journal.submitted_abstract') }}</h2></div></div><h3>{{ $submission->title }}</h3><p>{!! nl2br(e($submission->abstract)) !!}</p><div class="journal-submission-keywords">@foreach($submission->keywords as $keyword)<span>{{ $keyword }}</span>@endforeach</div></section>
<section class="data-card"><div class="data-card-header"><div><h2>{{ __('journal.disclosures') }}</h2></div></div><dl class="journal-facts">@foreach(['conflicts','funding','ethics'] as $field)<div><dt>{{ __('journal.'.$field) }}</dt><dd>{{ $submission->declarations[$field]??'—' }}</dd></div>@endforeach</dl></section>
</div>
@endsection
