@extends('layouts.articles')
@section('title', $currentSection?->localized('name') ?: __('public_site.articles.public_title'))
@section('description', $currentSection?->localized('description') ?: __('public_site.articles.meta_description'))
@section('content')
<section class="journal-page-head"><div class="public-container"><span>IUOAMC · EDITORIAL</span><h1>{{ $currentSection?->localized('name') ?: __('public_site.articles.public_title') }}</h1><p>{{ $currentSection?->localized('description') ?: __('public_site.articles.public_intro') }}</p></div></section>
<section class="journal-catalog public-container"><header class="journal-section-heading"><div><span>{{ __('public_site.articles.latest') }}</span><h2>{{ __('public_site.articles.editorial_library') }}</h2></div><form method="get" role="search"><input name="q" maxlength="160" value="{{ $filters['q']??'' }}" placeholder="{{ __('public_site.articles.search') }}"><button>{{ __('journal.search') }}</button></form></header>
<nav class="journal-section-filter"><a class="{{ !$currentSection?'active':'' }}" href="{{ route('public.articles.index',['locale'=>app()->getLocale()]) }}">{{ __('public_site.articles.all_sections') }}</a>@foreach($sections as $section)<a class="{{ $currentSection?->is($section)?'active':'' }}" href="{{ route('public.articles.sections.show',['locale'=>app()->getLocale(),'section'=>$section]) }}">{{ $section->localized('name') }}</a>@endforeach</nav>
<div class="journal-article-grid">@forelse($articles as $article)<article class="journal-card">@if($article->coverUrl())<a class="journal-card-cover" href="{{ route('public.articles.show',['locale'=>app()->getLocale(),'article'=>$article]) }}"><img src="{{ $article->coverUrl() }}" alt="{{ $article->localized('image_alt') }}" loading="lazy"></a>@endif<div class="journal-card-meta"><span class="journal-type">{{ $article->section?->localized('name') }}</span><time>{{ $article->published_at?->format('Y-m-d') }}</time></div><h3><a href="{{ route('public.articles.show',['locale'=>app()->getLocale(),'article'=>$article]) }}">{{ $article->localized('title') }}</a></h3><p>{{ $article->localized('excerpt') }}</p><div class="journal-byline"><span>{{ $article->author_name }}</span><span>{{ __('public_site.articles.reading_minutes',['minutes'=>$article->reading_minutes]) }}</span></div><a class="journal-read" href="{{ route('public.articles.show',['locale'=>app()->getLocale(),'article'=>$article]) }}">{{ __('journal.read_article') }} →</a></article>@empty<div class="journal-empty"><strong>{{ __('public_site.articles.empty_public') }}</strong></div>@endforelse</div>{{ $articles->links() }}</section>
@endsection
