@extends('layouts.articles')
@section('title', $article->localized('seo_title') ?: $article->localized('title'))
@section('description', $article->localized('seo_description') ?: $article->localized('excerpt'))
@section('og_type','article')
@push('metadata')<meta property="article:published_time" content="{{ $article->published_at?->toIso8601String() }}"><meta property="article:modified_time" content="{{ $article->updated_at?->toIso8601String() }}">@if($article->section)<meta property="article:section" content="{{ $article->section->localized('name') }}">@endif @foreach((($article->tags??[])[app()->getLocale()]??[]) as $tag)<meta property="article:tag" content="{{ $tag }}">@endforeach @if($article->coverUrl())<meta property="og:image" content="{{ $article->coverUrl() }}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="{{ $article->coverUrl() }}">@endif
@php($schema=['@context'=>'https://schema.org','@type'=>'Article','headline'=>$article->localized('title'),'description'=>$article->localized('excerpt'),'datePublished'=>$article->published_at?->toIso8601String(),'dateModified'=>$article->updated_at?->toIso8601String(),'articleSection'=>$article->section?->localized('name'),'keywords'=>(($article->tags??[])[app()->getLocale()]??[]),'author'=>['@type'=>'Person','name'=>$article->author_name],'publisher'=>['@type'=>'Organization','name'=>$siteProfile['legal_name'],'url'=>route('public.home',['locale'=>app()->getLocale()]),'logo'=>['@type'=>'ImageObject','url'=>asset($siteProfile['primary_logo'])]],'image'=>$article->coverUrl(),'mainEntityOfPage'=>url()->current(),'sameAs'=>$article->source_url])
<script type="application/ld+json" nonce="{{ request()->attributes->get('csp_nonce') }}">{!! json_encode($schema,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>@endpush
@section('content')<article class="journal-article public-container"><nav class="journal-breadcrumb"><a href="{{ route('public.articles.index',['locale'=>app()->getLocale()]) }}">{{ __('public_site.articles.public_title') }}</a>@if($article->section)<span>/</span><a href="{{ route('public.articles.sections.show',['locale'=>app()->getLocale(),'section'=>$article->section]) }}">{{ $article->section->localized('name') }}</a>@endif</nav><header class="journal-article-header"><span class="journal-type">{{ $article->section?->localized('name') }}</span><h1>{{ $article->localized('title') }}</h1><p class="journal-subtitle">{{ $article->localized('excerpt') }}</p><div class="journal-byline"><strong>{{ $article->author_name }}</strong><time datetime="{{ $article->published_at?->toDateString() }}">{{ $article->published_at?->format('Y-m-d') }}</time><span>{{ __('public_site.articles.reading_minutes',['minutes'=>$article->reading_minutes]) }}</span></div><a class="journal-read" href="{{ route('public.articles.pdf',['locale'=>app()->getLocale(),'article'=>$article]) }}">{{ __('public_site.articles.download_pdf') }}</a></header>@if($article->coverUrl())<figure class="journal-article-cover"><img src="{{ $article->coverUrl() }}" alt="{{ $article->localized('image_alt') }}" fetchpriority="high"></figure>@endif<section class="journal-body">{!! $formattedBody !!}</section>
@php($tags=($article->tags??[])[app()->getLocale()]??[])@if($tags)<div class="journal-card-sections">@foreach($tags as $tag)<span>#{{ $tag }}</span>@endforeach</div>@endif
<section class="journal-author-profile"><span>{{ __('public_site.articles.author') }}</span><h2>{{ $article->author_name }}</h2>@if($article->localized('author_biography'))<p>{{ $article->localized('author_biography') }}</p>@endif<small>{{ __('public_site.articles.published_by') }} {{ $article->publisher_name }}</small></section>
@if($article->source_url)<section class="journal-author-profile"><span>{{ __('public_site.articles.legacy_source') }}</span><p>{{ __('public_site.articles.originally_published') }} {{ $article->original_published_at?->format('Y-m-d') }}</p><a href="{{ $article->source_url }}" rel="noopener noreferrer">{{ __('public_site.articles.open_legacy_source') }}</a></section>@endif
@if($related->isNotEmpty())<section class="journal-related"><h2>{{ __('public_site.articles.related') }}</h2><div class="journal-role-grid">@foreach($related as $item)<article><span>{{ $item->section?->localized('name') }}</span><h3><a href="{{ route('public.articles.show',['locale'=>app()->getLocale(),'article'=>$item]) }}">{{ $item->localized('title') }}</a></h3><p>{{ $item->localized('excerpt') }}</p></article>@endforeach</div></section>@endif</article>@endsection
